config/routes.rb
Rippler::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }

  resources :services, :only => %w[index show]

  namespace :make do
    resources :services
    resources :entries, :only => %w[update]
  end

  resources :entries, :only => %w[index new create]
  resources :users, :only => %w[edit update]

  get "home" => "home#index"
  get "mypage" => "mypage#index"

  root :to => 'mypage#index'

end

app/models/entry.rb
# -*- coding: utf-8 -*-
class Entry < ActiveRecord::Base
  attr_accessible :content, :service_id, :approve_flg
  belongs_to :user
  belongs_to :service

  validates :content, :presence => true

  def user_name
    self.user.name
  end

  def service_name
    self.service.name
  end

  def approval_status
    if self.approve_flg == true
      "承認済み"
    else
      if self.created_at < Date.today - 7.day
        "非承認"
      else
        "承認待ち"
      end
    end
  end
end

app/models/make_user.rb
class MakeUser < ActiveRecord::Base
  attr_accessible :user_id, :service_id

  belongs_to :service
  belongs_to :user
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :name, :url, :summary, :introduction, :category
  has_many :make_users
  has_many :users, :through => :make_users
  has_many :entries

  CATEGORY_LIST = %w(education life).freeze

  scope :category_services, lambda{ |category|
    where(:category => category)
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :locale
  # attr_accessible :title, :body

  has_many :make_users
  has_many :services, :through => :make_users
  has_many :entries

  def make_user?
    MakeUser.where(:user_id => self.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
  prepend_before_filter :set_locale

  def set_locale
    I18n.locale = params[:lang] || get_locale_from_current_user || get_locale_from_header || I18n.default_locale
    if current_user && current_user.locale.blank?
      current_user.update_attributes({ :locale => I18n.locale.to_s })
    end
  end

  private
  def get_locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

  def get_locale_from_current_user
    locale = current_user.try(:locale)
    locale if locale && available_locales.include?(locale.to_sym)
  end

  def self.available_locales
    I18n.available_locales
  end

  def available_locales
    @i18n_available_locales ||= self.class.available_locales
  end
end

app/controllers/entries_controller.rb
# -*- coding: utf-8 -*-
class EntriesController < ApplicationController
  layout false, :only => %w[new create]

  skip_before_filter :authenticate_user!
  before_filter :entry_authenticate_user!

  def index
    @entries = current_user.entries.order("created_at DESC")
  end

  def new
    @entry = current_user.entries.build
    @service_url = params[:url]
  end

  def create
    @entry = current_user.entries.build(params[:entry])
    @entry.service = Service.find_by_url(fix_url(params[:url]))
    if @entry.save
      redirect_to new_entry_path, :notice => "フィードバックを送りました。"
    else
      render "new"
    end
  end

  private
  def entry_authenticate_user!
    redirect_to new_user_session_path unless user_signed_in?
  end

  def fix_url(params_url)
    params_url.match(/^([a-z]+):\/\/([a-zA-Z0-9:.-]+)\//)[0]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  layout false
  def index
    @hot_services = Service.all.slice(0..7)
  end
end

app/controllers/make/entries_controller.rb
class Make::EntriesController < ApplicationController
  def update
    @entry = current_user.services.find(params[:service_id]).entries.find(params[:id])
    if @entry.update_attributes(params[:entry])
      redirect_to make_service_path(params[:service_id])
    end
  end
end

app/controllers/make/services_controller.rb
# -*- coding: utf-8 -*-
class Make::ServicesController < ApplicationController
  def index
    @services = current_user.services
  end

  def new
    @service = Service.new
  end

  def edit
    @service = current_user.services.find(params[:id])
  end

  def show
    @service = current_user.services.find(params[:id])
    @entries = @service.entries.order("created_at DESC")
  end

  def create
    @service = Service.new(params[:service])
    @service.make_users.build(:user_id => current_user.id)

    if @service.save
      redirect_to make_services_path, :notice => "サービスを追加しました。"
    else
      render "new"
    end
  end

  def update
    @service = current_user.services.find(params[:id])

    if @service.update_attributes(params[:service])
      redirect_to make_service_path(@service)
    else
      render "edit"
    end
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
    @approve_entry_count = current_user.entries.where(:approve_flg => true).count
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @hot_services = [Service.all[0], Service.all[1]]
    @all_entries = Entry.order("created_at DESC")
    @category_services = Service.category_services(params[:category]).each_slice(4).to_a if params[:category]
  end

  def show
    @service = Service.find(params[:id])
    @make_users = @service.users
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_path
    else
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def view_select_language
    t('views.commons.language') + ': ' +  t("views.commons.#{I18n.locale || I18n.default_locale}")
  end

  def resource
    @resource ||= User.new
  end

  def resource_name
    :user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/services_helper.rb
module ServicesHelper

  def feedback_time(time)
    diff_time = (Time.now - time).ceil
    if diff_time < 60
      "#{diff_time}s"
    elsif diff_time >= 60 && diff_time < 3600
      "#{diff_time / 60}m"
    elsif diff_time >= 3600 && diff_time < 86400
      "#{diff_time / 3600}h"
    elsif diff_time >= 86400
      "#{diff_time / 86400}d"
    end
  end
end

app/views/entries/index.html.haml
.page-header
  %h2= t('views.entries.title')

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th= t('views.services.detail.name')
      %th= t('views.entries.content')
      %th 承認状況
  %tbody
    - @entries.each do |entry|
      %tr
        %td= entry.service.name
        %td= entry.content
        %td= entry.approval_status

app/views/entries/new.html.haml
#rippler-embed-form
  - if flash[:notice]
    = flash[:notice]

  = form_for @entry do |f|
    = f.text_area :content
    = hidden_field_tag :url, @service_url
    = f.submit t('views.my_page.users.action'), :class => "btn"

  ユーザ名
  = current_user.name

app/views/home/index.html.haml
!!!
%html

  %head
    %title
      Rippler
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.home-body
    .navbar.navbar-top.home-header
      .container
        = link_to "Rippler", root_path, :class => "brand"
        .pull-right
          %ul.nav
            %li.dropdown
              = link_to view_select_language, "#", { :class => "dropdown-toggle", "data-toggle" => "dropdown" }
              %ul{ :class => "dropdown-menu", :role => "menu", "aria-labelledby" => "dLabel" }
                %li
                  - ["ja", "en"].each do |lang|
                    = link_to t("views.commons.#{lang}"), request.path + "?lang=#{lang}"
    .home-introduction
      .container
        = link_to t('views.commons.sign_in'), "#myModal", :class => "btn btn-primary", "data-toggle" => "modal"
        %div{ :id => "myModal", :class => "modal hide fade", :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true", :style => "display: none;" }
          .modal-header
            %button{ :type => "button", :class => "close", "data-dismiss" => "modal", "aria-hidden" => "true" }
              ×
          .modal-body
            = render :template => "users/sessions/new"
    .home-services
      .container
        %ul
          - @hot_services.each do |service|
            %li
              = image_tag "education.jpeg"
              = link_to service.name, service_path(service.id)
    .home-footer

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      Rippler
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "Rippler", root_path, :class => "brand"
          .nav-collapse.collapse
            - if user_signed_in?
              .navbar-text
                %ul.nav
                  %li= link_to t('views.my_page.title'), mypage_path
              .navbar-text.pull-right
                %ul.nav
                  %li.dropdown
                    = link_to "#{current_user.name} <b class='caret'></b>".html_safe, "#", { :class => "dropdown-toggle", "data-toggle" => "dropdown" }
                    %ul{ :class => "dropdown-menu", :role => "menu", "aria-labelledby" => "dLabel" }
                      %li
                        = link_to t('views.users.edit.title'), edit_user_path(current_user)
                      %li.divider
                      %li.presentation
                        = link_to t('views.commons.sign_out'), destroy_user_session_path, :method => "delete"

            - else
              .pull-right
                %ul.nav
                  %li.dropdown
                    = link_to view_select_language, "#", { :class => "dropdown-toggle", "data-toggle" => "dropdown" }
                    %ul{ :class => "dropdown-menu", :role => "menu", "aria-labelledby" => "dLabel" }
                      %li
                        - ["ja", "en"].each do |lang|
                          = link_to t("views.commons.#{lang}"), request.path + "?lang=#{lang}"
    .container
      = yield

app/views/make/services/_form.html.haml
= form_for ["make", @service], :html => { :class => "form-horizontal" } do |f|
  .control-group
    = f.label :name, t('views.services.detail.name'), :class => "control-label"
    .controls
      = f.text_field :name
  .control-group
    = f.label :url, "URL", :class => "control-label"
    .controls
      = f.text_field :url
  .control-group
    = f.label :summary, t('views.services.detail.summary'), :class => "control-label"
    .controls
      = f.text_field :summary
  .control-group
    = f.label :introduction, t('views.services.detail.introduction'), :class => "control-label"
    .controls
      = f.text_field :introduction
  .control-group
    = f.label :category, t('views.services.detail.category'), :class => "control-label"
    .controls
      = f.select :category, Service::CATEGORY_LIST
  .control-group
    .controls
      = f.submit t('helpers.submit.create'), :class => "btn btn-primary"

app/views/make/services/edit.html.haml
.page-header
  %h2 登録情報の変更
%p
  = link_to "<< 開発中のサービス一覧に戻る", make_services_path, :class => "btn"

= render "form"

app/views/make/services/index.html.haml
.page-header
  %h2= t('views.services.list')

- if flash[:notice]
  = flash[:notice]

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th #
      %th= t('views.services.detail.name')
      %th URL
      %th

  %tbody
    - @services.each_with_index do |service, i|
      %tr
        %td= i + 1
        %td= service.name
        %td= service.url
        %td
          = link_to "フィードバックの確認・承認", make_service_path(service.id)
          |
          = link_to t('views.services.edit.title'), edit_make_service_path(service.id)

= link_to t('views.services.new.title'), new_make_service_path, :class => "btn"

app/views/make/services/new.html.haml
.page-header
  %h2= t('views.services.new.title')
%p
  = link_to "<< 開発中のサービス一覧に戻る", make_services_path, :class => "btn"

= render "form"

app/views/make/services/show.html.haml
.page-header
  %h2 フィードバックの確認
%p
  = link_to "<< 開発中のサービス一覧に戻る", make_services_path, :class => "btn"

%table.table.table-bordered.table-striped
  %tbody
    - @entries.each do |entry|
      %tr.feedback-box
        %td.feedback-desc
          %p
            = entry.content
          .feedback-user
            = entry.user_name
            = feedback_time(entry.created_at)
        %td
          - if entry.approve_flg
            承認済み
          - else
            = form_for ["make", entry] do |f|
              = hidden_field_tag :service_id, params[:id]
              = f.hidden_field :approve_flg, :value => true
              = f.submit "承認する", :class => "btn btn-primary"

app/views/mypage/index.html.haml
.page-header
  %h2= t('views.my_page.title')

.row
  .span6
    .mypage-layout
      %h3
        = t('views.my_page.users.name')
        = "(#{@approve_entry_count})"
      = link_to t('views.my_page.users.action'), services_path, :class => "btn btn-primary"
      = link_to t('views.entries.title'), entries_path, :class => "btn"
  .span6
    .mypage-layout
      %h3= t('views.my_page.developers.name')
      = link_to t('views.my_page.developers.action'), make_services_path, :class => "btn btn-primary"

app/views/services/_category_services.html.haml
- if user_signed_in?
  %table.table.table-bordered
    %thead
      %tr
        %th{:colspan => 4}
          = t('views.services.recommend')
    %tbody
      %tr
        - @hot_services.each_with_index do |service, i|
          %td.hot-image
            - if i == 0
              = image_tag "deshiel.jpeg"
            - elsif i == 1
              = image_tag "search.jpeg"
          %td.hot-desc
            %h5
              = link_to service.name, service_path(service)
            = service.summary
            %br
            = t('views.services.developer')
            ：
            = service.users.map{|user| user.name}.join(",")
%table.table.table-bordered
  %thead
    %tr
      %th{:colspan => 4}
        = t('views.services.by_category')
        （
        = t("views.services.category.#{params[:category]}")
        ）
        = link_to t('views.services.all_category'), services_path
  %tbody
    - @category_services.each do |service_arr|
      %tr
        - service_arr.each do |service|
          %td.table-divided
            = image_tag "education.jpeg"
            = link_to service.name, service_path(service.id)

app/views/services/index.html.haml
.row-fluid
  - if params[:category]
    = render "category_services"
  - else
    - if user_signed_in?
      %table.table.table-bordered
        %thead
          %tr
            %th{:colspan => 4}
              = t('views.services.recommend')
        %tbody
          %tr
            - @hot_services.each_with_index do |service, i|
              %td.hot-image
                - if i == 0
                  = image_tag "deshiel.jpeg"
                - elsif i == 1
                  = image_tag "search.jpeg"
              %td.hot-desc
                %h5
                  = link_to service.name, service_path(service)
                = service.summary
                %br
                = t('views.services.developer')
                ：
                = service.users.map{|user| user.name}.join(",")
    - else
      .hero-unit
        %h2 New services! New experiences!
        %p
          まだ世の中に広まっていないサービスを通じて、未知の体験ができるプラットフォームです。
        = link_to t('views.commons.sign_in'), new_user_session_path(:params => {:lang => params[:lang]}), :class => "btn btn-primary"
    %table.table.table-bordered
      %thead
        %tr
          %th{:colspan => 4}
            = t('views.services.by_category')
      %tbody
        %tr
          %td.table-divided
            = image_tag "education.jpeg"
            = link_to t('views.services.category.education'), services_path(:category => "education")
          %td.table-divided
            = image_tag "life.jpeg"
            = link_to t('views.services.category.life'), services_path(:category => "life")
          %td.table-divided
            = image_tag "game.jpeg"
            = link_to t('views.services.category.game'), services_path(:category => "game")
          %td.table-divided
            = image_tag "business.jpeg"
            = link_to t('views.services.category.business'), services_path(:category => "business")
        %tr
          %td.table-divided
            = image_tag "music.jpeg"
            = link_to t('views.services.category.music'), services_path(:category => "music")
          %td.table-divided
            = image_tag "weather.jpeg"
            = link_to t('views.services.category.weather'), services_path(:category => "weather")
          %td.table-divided
            = image_tag "travel.jpeg"
            = link_to t('views.services.category.traveling'), services_path(:category => "traveling")
          %td.table-divided
            = image_tag "efficient.jpeg"
            = link_to t('views.services.category.work_efficiency'), services_path(:category => "work_efficiency")
        %tr
          %td.table-divided
            = image_tag "finance.jpeg"
            = link_to t('views.services.category.finance'), services_path(:category => "finance")

app/views/services/show.html.haml
.page-header
  - if @service.name == "Deshiel"
    = image_tag "deshiel.jpeg"
  - elsif @service.name == "My-Dictionary"
    = image_tag "search.jpeg"
  - else
    = image_tag "lift.jpeg"
  %h2= @service.name
  .service-link
    = link_to t('views.services.detail.experience'), @service.url, :class => "btn btn-primary", :target => "_blank"

%p
  = link_to "<< #{t('views.commons.back')}", :back, :class => "btn"
.main-frame
  %h5= t('views.services.detail.summary')
  = @service.summary
  %h5= t('views.services.detail.introduction')
  = @service.introduction
  %h5= t('views.services.developer')
  - @make_users.each do |make_user|
    = make_user.name

app/views/users/edit.html.haml
.page-header
  %h2= t('views.users.edit.title')
%p
  = link_to "<< #{t('views.commons.back')}", :back, :class => "btn"

= form_for current_user, :html => { :class => "form-horizontal" } do |f|
  .control-group
    = f.label :email, :class => "control-label"
    .controls
      = f.text_field :email
  .control-group
    = f.label :name, :class => "control-label"
    .controls
      = f.text_field :name
  .control-group
    = f.label :locale, :class => "control-label"
    .controls
      = f.select :locale, [[t('views.commons.en'), "en"], [t('views.commons.ja'), "ja"]]
  .control-group
    .controls
      = f.submit t('helpers.submit.update'), :class => "btn btn-primary"